name: update-bookmarks

on:
  push:
    paths:
      - 'config/browser/bookmarks.csv'
  workflow_dispatch:

jobs:
  update-bookmarks:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: generate-bookmarks
      run: |
        cd scripts
        python bookmarks.py

    - name: check-for-changes
      id: changes
      run: |
        if git diff --quiet config/browser/bookmarks.html; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: write-changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config user.name github-actions
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add config/browser/bookmarks.html
        git commit -m "auto: update bookmarks.html"
        git push
